// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gngbfwlgvbnbcolbmhdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZ2Jmd2xndmJuYmNvbGJtaGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTUyMzksImV4cCI6MjA2MDA5MTIzOX0.vmYxp88msjWxzXD3yTHAePEvje4tWLWflr1MzPvUkuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);